#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#setxkbmap -option terminate:ctrl_alt_bksp
if [[ "$(</sys/class/drm/card1-HDMI-A-1/status)" = "connected" ]]
then
	export TABBED="$(/usr/local/bin/tabbed -g 1920x1080 -d -o black)"
	countab &
	xsetroot -cursor_name left_ptr
	xrandr --output eDP-1 --off
	export DISPLAY=${DISPLAY}.1
fi
systemctl --user import-environment
systemctl --user start startx.target
xinput set-prop 'ETPS/2 Elantech Touchpad' "libinput Tapping Enabled" 1
xset r 66
xset -r 118
xset dpms 0 0 0
xset b on
exec /usr/local/bin/openbox-session
